package rules

// BuiltinRules returns the default set of secret detection rules.
func BuiltinRules() []Rule {
	return []Rule{
		{
			ID:         "aws-access-key",
			Name:       "AWS Access Key ID",
			Pattern:    `AKIA[0-9A-Z]{16}`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"AKIA"},
		},
		{
			ID:         "aws-secret-key",
			Name:       "AWS Secret Access Key",
			Pattern:    `(?i)aws_secret_access_key\s*[=:]\s*[A-Za-z0-9/+=]{40}`,
			EntropyMin: 4.0,
			Severity:   "high",
			Keywords:   []string{"aws_secret_access_key"},
		},
		{
			ID:         "azure-token",
			Name:       "Azure Tenant/Client Secret",
			Pattern:    `(?i)azure[_\-]?(?:tenant|client)[_\-]?secret\s*[=:]\s*[A-Za-z0-9\-_]{20,}`,
			EntropyMin: 3.5,
			Severity:   "high",
			Keywords:   []string{"azure"},
		},
		{
			ID:         "gcp-service-account",
			Name:       "GCP Service Account Key",
			Pattern:    `(?i)"type"\s*:\s*"service_account"`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"service_account"},
		},
		{
			ID:         "github-token",
			Name:       "GitHub Token",
			Pattern:    `gh[psoru]_[A-Za-z0-9_]{36,255}`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"ghp_", "ghs_", "gho_", "ghu_", "ghr_"},
		},
		{
			ID:         "gitlab-token",
			Name:       "GitLab Token",
			Pattern:    `glpat-[A-Za-z0-9\-_]{20,}`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"glpat-"},
		},
		{
			ID:         "bitbucket-token",
			Name:       "Bitbucket Token",
			Pattern:    `(?i)bitbucket[_\-]?token\s*[=:]\s*[A-Za-z0-9\-_]{20,}`,
			EntropyMin: 3.5,
			Severity:   "high",
			Keywords:   []string{"bitbucket"},
		},
		{
			ID:         "slack-token",
			Name:       "Slack Token",
			Pattern:    `xox[baprs]-[A-Za-z0-9\-]{10,}`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"xoxb-", "xoxa-", "xoxp-", "xoxr-", "xoxs-"},
		},
		{
			ID:         "discord-token",
			Name:       "Discord Token",
			Pattern:    `(?i)discord[_\-]?token\s*[=:]\s*[A-Za-z0-9\-_._]{20,}`,
			EntropyMin: 3.5,
			Severity:   "high",
			Keywords:   []string{"discord"},
		},
		{
			ID:         "mongodb-uri",
			Name:       "MongoDB Connection URI",
			Pattern:    `mongodb(\+srv)?://[A-Za-z0-9\-_]+:[A-Za-z0-9\-_!@#$%^&*]+@[A-Za-z0-9\-_.]+`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"mongodb://", "mongodb+srv://"},
		},
		{
			ID:         "postgresql-uri",
			Name:       "PostgreSQL Connection URI",
			Pattern:    `postgres(ql)?://[A-Za-z0-9\-_]+:[A-Za-z0-9\-_!@#$%^&*]+@[A-Za-z0-9\-_.]+`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"postgres://", "postgresql://"},
		},
		{
			ID:         "mysql-uri",
			Name:       "MySQL Connection URI",
			Pattern:    `mysql://[A-Za-z0-9\-_]+:[A-Za-z0-9\-_!@#$%^&*]+@[A-Za-z0-9\-_.]+`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"mysql://"},
		},
		{
			ID:         "stripe-key",
			Name:       "Stripe Secret Key",
			Pattern:    `sk_live_[0-9a-zA-Z]{24,}`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"sk_live_"},
		},
		{
			ID:         "private-key",
			Name:       "Private Key",
			Pattern:    `-----BEGIN (?:RSA |EC |DSA )?PRIVATE KEY-----`,
			EntropyMin: 0,
			Severity:   "high",
			Keywords:   []string{"PRIVATE KEY"},
		},
		{
			ID:         "generic-high-entropy",
			Name:       "Generic High-Entropy String",
			Pattern:    `(?i)(?:password|passwd|secret|token|key|api[_\-]?key)\s*[=:]\s*['"]?[A-Za-z0-9\-_./+=]{20,}['"]?`,
			EntropyMin: 4.5,
			Severity:   "medium",
			Keywords:   []string{"password", "secret", "token", "api_key", "apikey"},
		},
	}
}
